name: "jaffle_semantic_layer_testing"
version: "1.0.0"
config-version: 2

profile: duckdb
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["jaffle-data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"
  "dbt_date:time_zone": "America/Los_Angeles"

models:
  staging:
    +materialized: view
  marts:
    +materialized: table
