name: CI

on: pull_request

jobs:
  dbt-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          pipx install meltano && meltano install
      - name: Install dbt Dependencies
        run: dbt deps
      - name: dbt Build
        run: dbt build
